name = "gulfislands-claim-processor"
main = "src/index.ts"
compatibility_date = "2024-02-18"

[[kv_namespaces]]
binding = "GULFISLANDS_CLAIMS"
id = "c1229d7774d64de4874b13655a88e549"

[vars]
ALLOWED_ORIGIN = "https://gulfislands.com"
SUPPORT_EMAIL = "support@natinternet.com"
MOSPARO_HOST = "https://mosparo.natinternet.com"
